name: Deploy API
on: [push]
jobs:

  build:
    
    name: Deploy API
    environment: iks
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get IAM token
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        API_HOST: ${{ secrets.APICHOST}}
      run: |
        mkdir ~/.apiconnect/
        touch ~/.apiconnect/token
         TOKEN=$(curl -sk "https://$API_HOST/api/cloud/provider/identity-providers" -H 'Accept: application/json' -H 'Content-Type: application/json' | jq '.results | .[] | .realm');

                  echo "${API_HOST}/api: |
                refresh_token: \"\"
                access_token: ${TOKEN}" > ~/.apiconnect/token 
          echo "Token : ${TOKEN} from apic: ${API_HOST}" 
          echo "value: ${API_HOST}"       
          echo ${{secrets.APICHOST}} | sed 's/./& /g'
