name: Deploy API
on: [push]
jobs:

  build:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get IAM token
      env:
        API_KEY: ${{ secrets.APICHOST }}
        API_HOST: api.${{ secrets.APICHOST}}
      run: |
        mkdir ~/.apiconnect/
        touch ~/.apiconnect/token
                  echo "${API_HOST}/api: |
                refresh_token: \"\"
                access_token: ${TOKEN}" > ~/.apiconnect/token 
          echo "Token : ${TOKEN} from apic: ${API_HOST}" 
          echo "host: ${{secrets.APICHOST}}"
          echo "env: ${env.API_HOST}"
          echo "value: ${API_HOST}"

        TOKEN=$(curl -sk "https://$API_HOST/api/cloud/provider/identity-providers" -H 'Accept: application/json' -H 'Content-Type: application/json' | jq '.results | .[] | .realm');
       
