name: Deploy API
on: [push]
jobs:

  build:
    
    name: Deploy API
    environment: iks
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get IAM token
      env:
        API_KEY: ${{ secrets.APICHOST }}
        API_HOST: api.${{ secrets.APICHOST}}
      run: |
        mkdir ~/.apiconnect/
        touch ~/.apiconnect/token
                  echo "${API_HOST}/api: |
                refresh_token: \"\"
                access_token: ${TOKEN}" > ~/.apiconnect/token 
          echo "Token : ${TOKEN} from apic: ${API_HOST}" 
          echo "env: ${env.API_HOST}"
          echo "value: ${API_HOST}"       
